name: review
channels:
    - nrel
    - defaults
    - conda-forge
dependencies:
    - addfips
    - dash
    - dash-bootstrap-components
    - flask-caching
    - h5py
    - numpy
    - pandas
    - pandarallel
    - pint
    - plotly
    - pyproj
    - pytest
    - python=3.11
    - python-dotenv
    - requests
    - scikit-learn
    - scipy
    - setuptools
    - tqdm
    - shapely
    - geopandas
    - us
    - pip
    - pip:
        - pygeopkg
