name: review-dev
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - dash>=2.3.0
  - dash-core-components
  - dash-html-components
  - dash-table
  - flask-caching
  - gunicorn
  - matplotlib
  - pandas
  - pip
  - pyproj
  - python>=3.9
  - python-dotenv
  - scikit-learn
  - spyder-kernels=2.2
  - tqdm
  - tk
  - werkzeug>=2.0.3
  - pip:
    - nbformat
    - requests
    - us
    - addfips
