name: review
channels:
    - conda-forge
    - nrel
dependencies:
    - python=3.9
    - addfips>=0.3.1,<1
    - colorama>=0.4.4,<1
    - dash>=2.3.0,<3
    - flask>=2.1.3,<3
    - flask-caching>=2.0.1,<3
    - geopandas>=0.12.2,<1
    - h5py>=3.8.0,<4
    - numpy>=1.22.3,<2
    - pandas>=1.5.3,<2
    - pandarallel>=1.6.1,<2
    - pint>=0.19.2,<1
    - plotly>=5.13.0,<6
    - pyproj>=3.3.0,<4
    - pytest>=7.1.2,<8
    - python-dotenv>=0.20.0,<1
    - requests>=2.27.1,<3
    - scipy>=1.10.0,<2
    - setuptools>=65.5.1,<66
    - tqdm>=4.64.1,<5
    - werkzeug>=2.0.3,<2.0.4
    - shapely>=2.0.0,<3
    - geoplot>=0.5.1,<1
    - openpyxl>=3.1.2,<4
    - xlrd>=2.0.1,<3
    - pip>=23.0.1,<24
    - pip:
        - -r requirements.txt
