name: Pytests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1

    - uses: nanasess/setup-chromedriver@v1
    - name: Install Chrome Driver
      run: chromedriver --url-base=/wd/hub &

    - name: Install Conda environment from environment.yml
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment.yml
        cache-environment: true

    - name: Install Package
      shell: powershell
      run: |
        python -m pip install .[dev]

    - name: Run Pytest
      shell: powershell
      run: |
        python -m pytest -v --disable-warnings
